# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  labels:
    label-one: "value-one"
  name: postgres-secondary-demo
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn-live'
    config.kubernetes.io/depends-on: sql.cnrm.cloud.google.com/namespaces/config-control/SQLInstance/postgres-secondary-1 # kpt-set: sql.cnrm.cloud.google.com/namespaces/config-control/SQLInstance/${db-instance-2}
spec:
  charset: UTF8
  collation: en_US.UTF8
  instanceRef:
    name: postgres-secondary # kpt-set: ${db-instance-2}
