apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: postgres-secondary # kpt-set: ${db-instance-2}
  namespace: config-control # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn-live'
    cnrm.cloud.google.com/project-id: "project-id" # kpt-set: ${project-id}
    config.kubernetes.io/depends-on: serviceusage.cnrm.cloud.google.com/namespaces/config-control/Service/gcp-ha-services-sqladmin
spec:
  databaseVersion: POSTGRES_9_6
  region: northamerica-northeast2
  settings:
    tier: db-custom-1-3840
    availabilityType: REGIONAL
    ipConfiguration:
      ipv4Enabled: false
      privateNetworkRef:
        name: gke-net
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: postgres-secondary-private-ip
  namespace: config-control # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn-live'
    cnrm.cloud.google.com/project-id: "project-id" # kpt-set: ${project-id}
spec:
  addressType: INTERNAL
  location: global
  purpose: VPC_PEERING
  prefixLength: 16
  networkRef:
    name: gke-net
