apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: innovapost-demo-services-anthos
  namespace: config-control # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/deletion-policy: 'false'
    cnrm.cloud.google.com/disable-dependent-services: 'false'
    blueprints.cloud.google.com/ownerReference: 'blueprints.cloud.google.com/ProjectServiceSet/innovapost-demo-services'
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
spec:
  resourceID: anthos.googleapis.com
  projectRef:
    external: my-awesome-project
