# Fortigate External IP reservation
# resource "google_compute_address" "ext_priv" {
#   count                  = 2

#   name                   = "${var.prefix}ip${count.index+1}-untrust-${local.region_short}"
#   region                 = var.region
#   address_type           = "INTERNAL"
#   subnetwork             = data.google_compute_subnetwork.subnets[0].id
# }
# Primary
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: perimeter-fgt-primary-ext-address
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: fgt-primary-ext-address
  address: 172.31.200.10
  addressType: INTERNAL
  location: northamerica-northeast1
  purpose: GCE_ENDPOINT
  subnetworkRef:
    name: perimeter-nane1-external-paz-snet
---
# Secondary
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: perimeter-fgt-secondary-ext-address
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: fgt-secondary-ext-address
  address: 172.31.200.11
  addressType: INTERNAL
  location: northamerica-northeast1
  purpose: GCE_ENDPOINT
  subnetworkRef:
    name: perimeter-nane1-external-paz-snet
---
# Fortigate Internal IP reservation
# resource "google_compute_address" "int_priv" {
#   count                  = 2

#   name                   = "${var.prefix}ip${count.index+1}-trust-${local.region_short}"
#   region                 = var.region
#   address_type           = "INTERNAL"
#   subnetwork             = data.google_compute_subnetwork.subnets[1].id
# }
# Primary
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: perimeter-fgt-primary-int-address
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: fgt-primary-int-address
  address: 172.31.201.10
  addressType: INTERNAL
  location: northamerica-northeast1
  purpose: GCE_ENDPOINT
  subnetworkRef:
    name: perimeter-nane1-internal-paz-snet
---
# Secondary
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: perimeter-fgt-secondary-int-address
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: fgt-secondary-int-address
  address: 172.31.201.11
  addressType: INTERNAL
  location: northamerica-northeast1
  purpose: GCE_ENDPOINT
  subnetworkRef:
    name: perimeter-nane1-internal-paz-snet
---
# Fortigate MGMT IP reservation
# resource "google_compute_address" "mgmt_priv" {
#   count                  = 2

#   name                   = "${var.prefix}ip${count.index+1}-mgmt-${local.region_short}"
#   region                 = var.region
#   address_type           = "INTERNAL"
#   subnetwork             = data.google_compute_subnetwork.subnets[3].id
# }
# Primary
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: perimeter-fgt-primary-mgmt-address
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: fgt-primary-mgmt-address
  address: 172.31.202.10
  addressType: INTERNAL
  location: northamerica-northeast1
  purpose: GCE_ENDPOINT
  subnetworkRef:
    name: perimeter-nane1-mgmt-rz-snet
---
# Secondary
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: perimeter-fgt-secondary-mgmt-address
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: fgt-secondary-mgmt-address
  address: 172.31.202.11
  addressType: INTERNAL
  location: northamerica-northeast1
  purpose: GCE_ENDPOINT
  subnetworkRef:
    name: perimeter-nane1-mgmt-rz-snet
---
# Fortigate Transit IP reservation
# resource "google_compute_address" "transit_priv" {
#   count                  = 2

#   name                   = "${var.prefix}ip${count.index+1}-transit-${local.region_short}"
#   region                 = var.region
#   address_type           = "INTERNAL"
#   subnetwork             = data.google_compute_subnetwork.subnets[1].id
# }
# Primary
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: perimeter-fgt-primary-transit-address
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: fgt-primary-transit-address
  address: 172.31.203.10
  addressType: INTERNAL
  location: northamerica-northeast1
  purpose: GCE_ENDPOINT
  subnetworkRef:
    name: perimeter-nane1-transit-paz-snet
---
# Secondary
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: perimeter-fgt-secondary-transit-address
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: fgt-secondary-transit-address
  address: 172.31.203.11
  addressType: INTERNAL
  location: northamerica-northeast1
  purpose: GCE_ENDPOINT
  subnetworkRef:
    name: perimeter-nane1-transit-paz-snet
---
# Internal Load Balancer IP Reservation
# resource "google_compute_address" "ilb" {
#   name                   = "${var.prefix}ip-ilb-trust-${local.region_short}"
#   region                 = var.region
#   address_type           = "INTERNAL"
#   subnetwork             = data.google_compute_subnetwork.subnets[1].id
# }
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: perimeter-ilb-address
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: ilb-address
  address: 172.31.201.30
  addressType: INTERNAL
  location: northamerica-northeast1
  subnetworkRef:
    name: perimeter-nane1-internal-paz-snet
---
# Internal Load Balancer - explicit proxy - IP Reservation
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: perimeter-ilb-proxy-address
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: ilb-proxy-address
  address: 172.31.201.35
  addressType: INTERNAL
  location: northamerica-northeast1
  subnetworkRef:
    name: perimeter-nane1-internal-paz-snet