---
# Log disk
# Create FortiGate instances with secondary logdisks and configuration. Everything 2 times (active + passive)
# resource "google_compute_disk" "logdisk" {
#   count                  = 2

#   name                   = "${var.prefix}disk-logdisk${count.index+1}-${local.zones_short[count.index]}"
#   size                   = 30
#   type                   = "pd-ssd"
#   zone                   = local.zones[count.index]
# }
# Primary
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: perimeter-fgt-primary-log-disk
  namespace: networking
spec:
  resourceID: fgt-primary-log-disk
  projectRef:
    external: perimeter-project-id # kpt-set: ${perimeter-project-id}
  size: 30
  type: pd-ssd
  location: northamerica-northeast1-a
---
# Secondary
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: perimeter-fgt-secondary-log-disk
  namespace: networking
spec:
  resourceID: fgt-secondary-log-disk
  projectRef:
    external: perimeter-project-id # kpt-set: ${perimeter-project-id}
  size: 30
  type: pd-ssd
  location: northamerica-northeast1-b
---