---
# External allow all
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: perimeter-allow-external-fwr
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: allow-external-fwr
  allow:
  - protocol: all
  direction: INGRESS
  networkRef:
    name: perimeter-global-external-vpc
  sourceRanges:
  - 0.0.0.0/0
---
# External Load Balancers health checks
# https://cloud.google.com/load-balancing/docs/health-checks#fw-rule
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: perimeter-elb-allow-health-checks-to-fortigate-fwr
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: elb-allow-health-checks-to-fortigate-fwr
  allow:
    - protocol: tcp
      ports:
       - "8008"
  networkRef:
    name: perimeter-global-external-vpc
  sourceRanges:
  - "35.191.0.0/16"
  - "130.211.0.0/22"
  targetServiceAccounts:
  - name: perimeter-fortigatesdn-sa
---
# Internal allow spokes to fortigates
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: perimeter-allow-spokes-to-fortigates-fwr
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: allow-spokes-to-fortigates-fwr
  allow:
  - protocol: all
  direction: INGRESS
  networkRef:
    name: perimeter-global-internal-vpc
  # TODO: once IP space is finalized, re-adjust this value to maybe allow only PAZ subnets
  sourceRanges:
  - 10.0.0.0/8
  targetServiceAccounts:
  - name: perimeter-fortigatesdn-sa
---
# Internal Load Balancers health checks
# https://cloud.google.com/load-balancing/docs/health-checks#fw-rule
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: perimeter-ilb-allow-health-checks-to-fortigate-fwr
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: ilb-allow-health-checks-to-fortigate-fwr
  allow:
    - protocol: tcp
      ports:
       - "8008"
  networkRef:
    name: perimeter-global-internal-vpc
  sourceRanges:
  - "35.191.0.0/16"
  - "130.211.0.0/22"
  targetServiceAccounts:
  - name: perimeter-fortigatesdn-sa
---
# Enable traffic on mgmt network for fortigates HA
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: perimeter-allow-fortigates-ha-fwr
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: allow-fortigates-ha-fwr
  direction: INGRESS
  allow:
    - protocol: all
  networkRef:
    name: perimeter-global-mgmt-vpc
  sourceServiceAccounts:
  - name: perimeter-fortigatesdn-sa
  targetServiceAccounts:
  - name: perimeter-fortigatesdn-sa
---