## Active Passive Cluster - Primary Node
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  name: perimeter-fgt-primary-instance
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: fgt-primary-instance
  description: Fortigate Primary Instance
  machineType: n2-standard-4
  zone: northamerica-northeast1-a
  canIpForward: true
  scheduling:
    automaticRestart: true
    onHostMaintenance: MIGRATE
    preemptible: false
  serviceAccount:
    serviceAccountRef:
      name: perimeter-fortigatesdn-sa
    scopes:
    - cloud-platform
  
  # TODO: Schedule
  # resourcePolicies:
  # - name: TBD
  
  # Create a new boot disk from an image
  bootDisk:
    autoDelete: true
    deviceName: persistent-disk-0
    initializeParams:
      type: pd-ssd
      sourceImageRef:
        external: image-path # kpt-set: ${fgt-primary-image}
  
  # Logging Disk from existing resource
  attachedDisk:
  - sourceDiskRef:
      name: perimeter-fgt-primary-log-disk
  
  networkInterface:
  # External
  - name: nic0
    networkRef:
      name: perimeter-global-external-vpc
    subnetworkRef:
      name: perimeter-nane1-external-paz-snet
    networkIpRef:
      name: perimeter-fgt-primary-ext-address
      kind: ComputeAddress
  # Internal
  - name: nic1
    networkRef:
      name: perimeter-global-internal-vpc
    subnetworkRef:
      name: perimeter-nane1-internal-paz-snet
    networkIpRef:
      name: perimeter-fgt-primary-int-address
      kind: ComputeAddress
  # Transit
  - name: nic2
    networkRef:
      name: perimeter-global-transit-vpc
    subnetworkRef:
      name: perimeter-nane1-transit-paz-snet
    networkIpRef:
      name: perimeter-fgt-primary-transit-address
      kind: ComputeAddress
  # MGMT
  - name: nic3
    networkRef:
      name: perimeter-global-mgmt-vpc
    subnetworkRef:
      name: perimeter-nane1-mgmt-rz-snet
    networkIpRef:
      name: perimeter-fgt-primary-mgmt-address
      kind: ComputeAddress

  tags:
  - internet-egress-route

  # Metadata to enable serial console and bootstrap FGT
  metadata:
  - key: serial-port-enable
    value: "TRUE"
  - key: license
    value: LICENSE # kpt-set: ${fgt-primary-license}
  - key: user-data
    value: |
      config system global
          set hostname "fgt-ap-primary"
          set admintimeout 60
          set timezone 12
      end
      config system admin
          edit "admin"
              set password fortinet
          next
      end
      config router static
          edit 10
              set device "port1"
              set gateway 172.31.200.1
          next
          edit 11
            set dst 172.31.200.0/24
            set device "port1"
            set gateway 172.31.200.1
          next
          edit 12
              set dst 35.191.0.0 255.255.0.0
              set comment "health check"
              set gateway 172.31.200.1
              set device "port1"
          next
          edit 13
              set dst 130.211.0.0 255.255.252.0
              set comment "health check"
              set gateway 172.31.200.1
              set device "port1"
          next
          edit 20
            set dst 172.31.201.1/32
            set device "port2"
          next
          edit 21
            set dst 172.31.201.0/24
            set device "port2"
            set gateway 172.31.201.1
          next
          edit 22
              set dst 35.191.0.0 255.255.0.0
              set comment "health check"
              set gateway 172.31.201.1
              set device "port2"
          next
          edit 23
              set dst 130.211.0.0 255.255.252.0
              set comment "health check"
              set gateway 172.31.201.1
              set device "port2"
          next
          edit 24
              set dst 10.0.0.0 255.0.0.0
              set comment "route to all spokes"
              set gateway 172.31.201.1
              set device "port2"
          next
          edit 30
              set dst 172.31.203.1/32
              set device "port3"
          next
          edit 31
            set dst 172.31.203.0/24
            set device "port3"
            set gateway 172.31.203.1
          next
      end
      config system probe-response
          set mode http-probe
          set http-probe-value OK
      end
      config system interface
        edit port1
              set description "external"
              set mode static
              set ip 172.31.200.10/32
              unset allowaccess
          next
          edit port2
              set description "internal"
              unset allowaccess
              set mode static
              set ip 172.31.201.10/32
              set explicit-web-proxy enable
              set secondary-IP enable
              # IP from internal load balancer
              config secondaryip
                  edit 1
                      set ip 172.31.201.30 255.255.255.255
                      set allowaccess probe-response
                  next
                  edit 2
                      set ip 172.31.201.35 255.255.255.255
                      set allowaccess probe-response
                  next
              end
          next
          edit "port3"
              set description "transit"
              unset allowaccess
              set mode static
              set ip 172.31.203.10/32
          next
          edit "port4"
              set description "management"
              set mode static
              set allowaccess ping https ssh fgfm
              set ip 172.31.202.10/32
          next
          edit "probe"
              set vdom "root"
              set ip 169.254.255.100 255.255.255.255
              set allowaccess probe-response
              set type loopback
          next
      end
      config system ha
          set group-name "fgt-ap-group"
          set mode a-p
          set hbdev "port4" 50
          # session-pickup has impact on cpu and may be disabled to improve performance
          set session-pickup enable
          set ha-mgmt-status enable
          config ha-mgmt-interfaces
              edit 1
                  set interface "port4"
                  set gateway 172.31.202.1
              next
          end
          set override enable
          set priority 200
          set unicast-hb enable
          set unicast-hb-peerip 172.31.202.11
          set unicast-hb-netmask 255.255.255.0
      end
      config system sdn-connector
          edit "gcp"
              set type gcp
              set ha-status enable
          next
      end
      config system dns
        set primary 169.254.169.254
        set protocol cleartext
        unset secondary
      end
      # explicit proxy for APPRZ and DATARZ workloads
      config system settings
          set gui-explicit-proxy enable
      end
      config web-proxy explicit
          set status enable
          set http-incoming-port 8080
          set https-incoming-port 8080
      end
---
# # Instance Template
# # Instance from Instance template was not functionning. The problem was that eventhough the 
# # NetworkIpRef was configured in the ComputeInstance, KCC wasn't applying that configuration 
# # resulting in instances with ephemeral IP
# #
# apiVersion: compute.cnrm.cloud.google.com/v1beta1
# kind: ComputeInstanceTemplate
# metadata:
#   name: fgt-primary-template
#   namespace: networking
#   annotations:
#     cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
# spec:
#   resourceID: fgt-primary-template
#   description: Fortigate Primary Instance Template
#   instanceDescription: FortiGate Primary Instance Template
#   machineType: n2-standard-4
#   region: northamerica-northeast1
#   canIpForward: true
#   scheduling:
#     automaticRestart: true
#     onHostMaintenance: MIGRATE
#     preemptible: false
#   serviceAccount:
#     scopes:
#     - https://www.googleapis.com/auth/cloud-platform
#     serviceAccountRef:
#       name: perimeter-fortigatesdn-sa
#   disk:
#     # Create a new boot disk from an image
#   - autoDelete: true
#     boot: true
#     deviceName: persistent-disk-0
#     type: PERSISTENT
#     sourceImageRef:
#       external: projects/fortigcp-project-001/global/images/fortinet-fgtondemand-722-20221004-001-w-license
#     # Logging Disk from existing resource
#   - autoDelete: false
#     sourceDiskRef:
#       name: perimeter-fgt-primary-log-disk
#   networkInterface:
#   - name: nic0
#     networkRef:
#       name: perimeter-global-external-vpc
#     subnetworkRef:
#       name: perimeter-nane1-external-paz-snet
#   - name: nic1
#     networkRef:
#       name: perimeter-global-internal-vpc
#     subnetworkRef:
#       name: perimeter-nane1-internal-paz-snet
#   - name: nic2
#     networkRef:
#       name: perimeter-global-transit-vpc
#     subnetworkRef:
#       name: perimeter-nane1-transit-paz-snet
#   - name: nic3
#     networkRef:
#       name: perimeter-global-mgmt-vpc
#     subnetworkRef:
#       name: perimeter-nane1-mgmt-rz-snet
#   tags:
#   - internet-egress-route
#   # Metadata to bootstrap FGT
#   metadata:
#   - key: serial-port-enable
#     value: "TRUE"
#   - key: user-data
#     value: "config system global\r\n    set hostname \"fgt-ap-primary\"\r\n    set admintimeout 60\r\nend\r\nconfig system admin\r\n    edit \"admin\"\r\n        set password fortinet\r\n    next\r\nend\r\nconfig router static\r\n    edit 10\r\n        set device \"port1\"\r\n        set gateway 172.31.200.1\r\n    next\r\n    edit 11\r\n      set dst 172.31.200.0/24\r\n      set device \"port1\"\r\n      set gateway 172.31.200.1\r\n    next\r\n    edit 12\r\n        set dst 35.191.0.0 255.255.0.0\r\n        set comment \"health check\"\r\n        set gateway 172.31.200.1\r\n        set device \"port1\"\r\n    next\r\n    edit 13\r\n        set dst 130.211.0.0 255.255.252.0\r\n        set comment \"health check\"\r\n        set gateway 172.31.200.1\r\n        set device \"port1\"\r\n    next\r\n    edit 20\r\n      set dst 172.31.201.1/32\r\n      set device \"port2\"\r\n    next\r\n    edit 21\r\n      set dst 172.31.201.0/24\r\n      set device \"port2\"\r\n      set gateway 172.31.201.1\r\n    next\r\n    edit 22\r\n        set dst 35.191.0.0 255.255.0.0\r\n        set comment \"health check\"\r\n        set gateway 172.31.201.1\r\n        set device \"port2\"\r\n    next\r\n    edit 23\r\n        set dst 130.211.0.0 255.255.252.0\r\n        set comment \"health check\"\r\n        set gateway 172.31.201.1\r\n        set device \"port2\"\r\n    next\r\n    edit 30\r\n        set dst 172.31.203.1/32\r\n        set device \"port3\"\r\n    next\r\n    edit 31\r\n      set dst 172.31.203.0/24\r\n      set device \"port3\"\r\n      set gateway 172.31.203.1\r\n    next\r\n    edit 40\r\n        set dst 172.31.202.1/32\r\n        set device \"port4\"\r\n    next\r\n    edit 41\r\n      set dst 172.31.202.0/24\r\n      set device \"port4\"\r\n      set gateway 172.31.202.1\r\n    next\r\nend\r\nconfig system probe-response\r\n    set mode http-probe\r\n    set http-probe-value OK\r\nend\r\nconfig system interface\r\n   edit port1\r\n        set description \"external\"\r\n        set mode static\r\n        set ip 172.31.200.10/32\r\n        unset allowaccess\r\n        next\r\n    edit port2\r\n        set description \"internal\"\r\n        unset allowaccess\r\n        set mode static\r\n        set ip 172.31.201.10/32\r\n        set secondary-IP enable\r\n        config secondaryip\r\n            edit 1\r\n                set ip 172.21.1.5 255.255.255.255\r\n                set allowaccess probe-response\r\n            next\r\n        end\r\n    next\r\n    edit \"port3\"\r\n        set description \"transit\"\r\n        unset allowaccess\r\n        set mode static\r\n        set ip 172.31.203.10/32\r\n    next\r\n    edit \"port4\"\r\n        set description \"management\"\r\n        set mode static\r\n        set allowaccess ping https ssh fgfm\r\n        set ip 172.31.202.10/32\r\n    next\r\n    edit \"probe\"\r\n        set vdom \"root\"\r\n        set ip 169.254.255.100 255.255.255.255\r\n        set allowaccess probe-response\r\n        set type loopback\r\n    next\r\nend\r\nconfig system ha\r\n    set group-name \"fgt-ap-group\"\r\n    set mode a-p\r\n    set hbdev \"port4\" 50\r\n    set session-pickup enable\r\n    set ha-mgmt-status enable\r\n    config ha-mgmt-interfaces\r\n        edit 1\r\n            set interface \"port4\"\r\n            set gateway 172.31.202.1\r\n        next\r\n    end\r\n    set override enable\r\n    set priority 100\r\n    set unicast-hb enable\r\n    set unicast-hb-peerip 172.31.202.11\r\n    set unicast-hb-netmask 255.255.255.0\r\nend\r\nconfig system sdn-connector\r\n    edit \"gcp\"\r\n        set type gcp\r\n        set ha-status enable\r\n    next\r\nend\r\nconfig system dns\r\n  set primary 169.254.169.254\r\n  set protocol cleartext\r\n  unset secondary\r\nend"
# ---
# # Compute Instance from template
# # resource "google_compute_instance_from_template" "active_fgt_instance" {
# #   name                     = "${var.name}-fgt-0-${module.random.random_string}"
# #   zone                     = element(data.google_compute_zones.available.names, 0)
# #   source_instance_template = google_compute_instance_template.active.self_link

# #   network_interface {
# #     network_ip = var.active_port1_ip
# #     network    = module.vpc.vpc_networks[0]
# #     subnetwork = module.subnet.subnets[0]
# #   }
# #   network_interface {
# #     network_ip = var.active_port2_ip
# #     network    = module.vpc.vpc_networks[1]
# #     subnetwork = module.subnet.subnets[1]
# #   }
# #   network_interface {
# #     network_ip = var.active_port3_ip
# #     network    = module.vpc.vpc_networks[2]
# #     subnetwork = module.subnet.subnets[2]
# #   }
# #   network_interface {
# #     network_ip = var.active_port4_ip
# #     network    = module.vpc.vpc_networks[3]
# #     subnetwork = module.subnet.subnets[3]
# #   }
# # }
# apiVersion: compute.cnrm.cloud.google.com/v1beta1
# kind: ComputeInstance
# metadata:
#   name: fgt-primary-instance
#   namespace: networking
#   annotations:
#     cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
# spec:
#   zone: northamerica-northeast1-a
#   instanceTemplateRef:
#     name: fgt-primary-template
#   networkInterface:
#     # External
#   - networkIpRef:
#       name: fgt-primary-ext-address
#       kind: ComputeAddress
#     stackType: "IPV4_ONLY"
#     subnetworkRef:
#       name: perimeter-nane1-external-paz-snet
#     # Internal
#   - networkIpRef:
#       name: fgt-primary-int-address
#       kind: ComputeAddress
#     # networkRef:
#     #   name: perimeter-global-internal-vpc
#     subnetworkRef:
#       name: perimeter-nane1-internal-paz-snet
#     # Transit
#   - networkIpRef:
#       name: fgt-primary-transit-address
#       kind: ComputeAddress
#     # networkRef:
#     #   name: perimeter-global-transit-vpc
#     subnetworkRef:
#       name: perimeter-nane1-transit-paz-snet
#     # MGMT
#   - networkIpRef:
#       name: fgt-primary-mgmt-address
#       kind: ComputeAddress
#     # networkRef:
#     #   name: perimeter-global-mgmt-vpc
#     subnetworkRef:
#       name: perimeter-nane1-mgmt-rz-snet
# ---
