# UnManaged Instance Group
# resource "google_compute_instance_group" "umig_active" {
#   name    = "${var.name}-unmig-0-${module.random.random_string}"
#   project = var.project
#   zone    = element(data.google_compute_zones.available.names, 0)
#   instances = matchkeys(
#     google_compute_instance_from_template.active_fgt_instance.*.self_link,
#     google_compute_instance_from_template.active_fgt_instance.*.zone,
#     [data.google_compute_zones.available.names[0]],
#   )
# }
# Primary
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceGroup
metadata:
  name: fgt-primary-umig
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
spec:
  resourceID: fgt-primary-umig
  zone: northamerica-northeast1-a
  instances:
  - name: fgt-primary-instance
---
# Secondary
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceGroup
metadata:
  name: fgt-secondary-umig
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
spec:
  resourceID: fgt-secondary-umig
  zone: northamerica-northeast1-b
  instances:
  - name: fgt-secondary-instance