apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata: # kpt-merge: config-control/gke-config-management
  name: gke-config-management
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn-live'
spec:
  projectRef:
    external: project-id # kpt-set: ${project-id}
  location: global
  # The resourceID must be "configmanagement" if you want to use Anthos config
  # management feature.
  resourceID: configmanagement
