apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata:
  name: servicemesh
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn-live'
spec:
  projectRef:
    external: project-id # kpt-set: ${project-id} 
  location: global
  resourceID: servicemesh
