# Persistent data disk
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: perimeter-mgmt-data-disk
  namespace: networking
spec:
  resourceID: mgmt-data-disk
  projectRef:
    external: perimeter-project-id # kpt-set: ${perimeter-project-id}
  size: 30
  type: pd-ssd
  location: northamerica-northeast1-a
---