# MGMT VPC
---
# IAP to Management VM - RDP
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: perimeter-iap-allow-rdp-to-managementvm-fwr
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: iap-allow-rdp-to-managementvm-fwr
  allow:
    - protocol: tcp
      ports:
       - "3389"
  networkRef:
    name: perimeter-global-mgmt-vpc
  sourceRanges:
  - "35.235.240.0/20"
  targetServiceAccounts:
  - name: perimeter-managementvm-sa
---
# Management VM to Fortigates - ICMP and TCP SSH, HTTPS
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: perimeter-managementvm-allow-ssh-https-to-fortigates-fwr
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: managementvm-allow-ssh-https-to-fortigates-fwr
  allow:
    - protocol: tcp
      ports:
       - "22"
       - "443"
    - protocol: icmp
  networkRef:
    name: perimeter-global-mgmt-vpc
  sourceServiceAccounts:
  - name: perimeter-managementvm-sa
  targetServiceAccounts:
  - name: perimeter-fortigatesdn-sa
