# GCP SA Management VM
# AC-2(A) - One GCP service account is created and attached to the management VM.
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: perimeter-managementvm-sa
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: perimeter-project-id # kpt-set: ${perimeter-project-id}
spec:
  resourceID: managementvm-sa
  displayName: Management VM
