apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata: # kpt-merge: config-control/anthos-config-management-2
  name: anthos-config-management-2
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn-live'
    config.kubernetes.io/depends-on: sourcerepo.cnrm.cloud.google.com/namespaces/config-control/SourceRepoRepository/demo-application,container.cnrm.cloud.google.com/namespaces/config-control/ContainerCluster/gke-net-na-ne-2
spec:
  projectRef:
    external: project-id # kpt-set: ${project-id}
  location: global
  membershipRef:
    name: gke-ne2
  featureRef:
    name: gke-config-management
  configmanagement:
    version: 1.11.2
    configSync:
      sourceFormat: unstructured
      git:
        gcpServiceAccountRef:
          external: config-sync-sa-gateway@project-id.iam.gserviceaccount.com # kpt-set: config-sync-sa-gateway@${project-id}.iam.gserviceaccount.com
        secretType: gcpserviceaccount
        policyDir: k8s-configs
        syncBranch: main
        syncRepo: https://source.developers.google.com/p/project-id/r/gcp-ha-infra # kpt-set: https://source.developers.google.com/p/${project-id}/r/gcp-ha-infra
    policyController:
      enabled: true
      referentialRulesEnabled: true
      logDeniesEnabled: true
      templateLibraryInstalled: true
      auditIntervalSeconds: "20"
    binauthz:
      enabled: true
    hierarchyController:
      enabled: false
      enablePodTreeLabels: false
      enableHierarchicalResourceQuota: false
