apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      image:
        imageType: distroless
    discoverySelectors:
    - matchLabels:
        istio-injection: enabled
kind: ConfigMap
metadata: # kpt-merge: istio-system/istio-asm-managed
  name: istio-asm-managed
  namespace: istio-system
