apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata: # kpt-merge: ${NAMESPACE}/${CLUSTER_NAME}-subnet
  name: gke-ne1-subnet # kpt-set: ${subnetwork-name}
  namespace: config-control # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: "project-id" # kpt-set: ${project-id}  
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn-live'
spec:
  ipCidrRange: 10.2.0.0/16 # kpt-set: ${subnet-cidr}
  networkRef:
    name: gke-net # kpt-set: ${network-name}
  region: northamerica-northeast1 # kpt-set: ${region}
  privateIpGoogleAccess: true # kpt-set: ${private-google-access}
  logConfig:
    aggregationInterval: INTERVAL_10_MIN # kpt-set: ${log-aggreation-interval}
    flowSampling: 0.5 # kpt-set: ${flow-sampling}
    metadata: INCLUDE_ALL_METADATA # kpt-set: ${log-metadata}
  secondaryIpRange:
    - ipCidrRange: 10.3.0.0/16 # kpt-set: ${gke-services-cidr}
      rangeName: servicesrange # kpt-set: ${gke-services-range-name}
    - ipCidrRange: 10.4.0.0/16 # kpt-set: ${gke-pod-cidr}
      rangeName: clusterrange # kpt-set: ${gke-pod-range-name}
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  labels:
    label-one: "value-one"
  name: gateway-proxy-only-subnet
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn-live'
spec:
  ipCidrRange: 10.50.0.0/23
  region: northamerica-northeast1
  description: Proxy-only
  purpose: INTERNAL_HTTPS_LOAD_BALANCER
  role: ACTIVE
  privateIpGoogleAccess: false
  networkRef:
    name: gke-net
