# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: ProjectServiceSet
metadata: # kpt-merge: config-control/gcp-ha-services
  name: gcp-ha-services
  namespace: config-control # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/deletion-policy: "false"
    config.kubernetes.io/local-config: "true"
    cnrm.cloud.google.com/disable-dependent-services: "false"
spec:
  services: # list of services to generate
    - compute.googleapis.com
    - bigquery.googleapis.com
    - pubsub.googleapis.com
    - container.googleapis.com
    - binaryauthorization.googleapis.com
    - artifactregistry.googleapis.com
    - anthos.googleapis.com
    - anthosconfigmanagement.googleapis.com
    - mesh.googleapis.com
    - sourcerepo.googleapis.com
    - gkehub.googleapis.com
    - multiclusteringress.googleapis.com
    - multiclusterservicediscovery.googleapis.com
    - trafficdirector.googleapis.com
    - containersecurity.googleapis.com
    - sqladmin.googleapis.com
    - cloudbuild.googleapis.com
    - servicenetworking.googleapis.com
    - clouddeploy.googleapis.com
    - containerscanning.googleapis.com
    - dns.googleapis.com
  projectID: project-id # kpt-set: ${project-id}
