# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# VPC - External
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata: # kpt-merge: networking/project-id-global-external-vpc
  name: project-id-global-external-vpc # kpt-set: ${project-id}-global-external-vpc
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
    config.kubernetes.io/depends-on: serviceusage.cnrm.cloud.google.com/namespaces/projects/Service/project-id-compute # kpt-set: serviceusage.cnrm.cloud.google.com/namespaces/projects/Service/${project-id}-compute
    internal.kpt.dev/upstream-identifier: 'compute.cnrm.cloud.google.com|ComputeNetwork|networking|project-id-global-external-vpc'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg'
spec:
  resourceID: global-external-vpc
  description: External VPC
  routingMode: GLOBAL
  autoCreateSubnetworks: false # SC-7
  deleteDefaultRoutesOnCreate: true # AC-4, SC-7(5)
---
# VPC - Internal
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata: # kpt-merge: networking/project-id-global-internal-vpc
  name: project-id-global-internal-vpc # kpt-set: ${project-id}-global-internal-vpc
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
    config.kubernetes.io/depends-on: serviceusage.cnrm.cloud.google.com/namespaces/projects/Service/project-id-compute # kpt-set: serviceusage.cnrm.cloud.google.com/namespaces/projects/Service/${project-id}-compute
    internal.kpt.dev/upstream-identifier: 'compute.cnrm.cloud.google.com|ComputeNetwork|networking|project-id-global-internal-vpc'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg'
spec:
  resourceID: global-internal-vpc
  description: Internal VPC
  routingMode: GLOBAL
  autoCreateSubnetworks: false # SC-7
  deleteDefaultRoutesOnCreate: true # AC-4, SC-7(5)
---
# VPC - Management
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata: # kpt-merge: networking/project-id-global-mgmt-vpc
  name: project-id-global-mgmt-vpc # kpt-set: ${project-id}-global-mgmt-vpc
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
    config.kubernetes.io/depends-on: serviceusage.cnrm.cloud.google.com/namespaces/projects/Service/project-id-compute # kpt-set: serviceusage.cnrm.cloud.google.com/namespaces/projects/Service/${project-id}-compute
    internal.kpt.dev/upstream-identifier: 'compute.cnrm.cloud.google.com|ComputeNetwork|networking|project-id-global-mgmt-vpc'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg'
spec:
  resourceID: global-mgmt-vpc
  description: Management VPC
  routingMode: GLOBAL
  autoCreateSubnetworks: false # SC-7
  deleteDefaultRoutesOnCreate: true # AC-4, SC-7(5)
---
# VPC - Transit
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata: # kpt-merge: networking/project-id-global-transit-vpc
  name: project-id-global-transit-vpc # kpt-set: ${project-id}-global-transit-vpc
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
    config.kubernetes.io/depends-on: serviceusage.cnrm.cloud.google.com/namespaces/projects/Service/project-id-compute # kpt-set: serviceusage.cnrm.cloud.google.com/namespaces/projects/Service/${project-id}-compute
    internal.kpt.dev/upstream-identifier: 'compute.cnrm.cloud.google.com|ComputeNetwork|networking|project-id-global-transit-vpc'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg'
spec:
  resourceID: global-transit-vpc
  description: Transit VPC
  routingMode: GLOBAL
  autoCreateSubnetworks: false # SC-7
  deleteDefaultRoutesOnCreate: true # AC-4, SC-7(5)
